layout_spectrum: 0.7807603
name: steveveilleuxphotography
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 0.910624
  lightness: 0.9420862
  saturation: 0.2023518
  rhythmicContrast: 0.2999844
  brandColors:
    - '#4067A2'
    - '#4A4339'
    - '#77A2CE'
    - '#908066'
    - '#E0CFAC'
typography_spectrum: 0.1314509
