layout_spectrum: 0.7807603
typography_spectrum: 0.1314509
color:
  lightness: 0.9420862
  brandStrength: 0.8852688
  saturation: 0.2023518
  rhythmicContrast: 0.2999844
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
name: steveveilleuxphotography
